from __future__ import annotations

from validator.java.ast.comments import (
    comment_body,
    has_task_reference,
    is_allowed_comment,
    is_deprecation_comment,
    is_gwt_marker_comment,
    is_javadoc_comment,
    is_orphan_todo_fixme,
    is_public_api_javadoc,
    is_suppression_comment,
    iter_comments,
)
from validator.java.ast.gwt import line_in_range, parse_gwt_section_line_ranges
from validator.java.ast.imports import collect_identifier_usages, iter_import_declarations
from validator.java.ast.methods import iter_method_declarations
from validator.java.ast.entities import (
    entity_class_name,
    find_jpa_entity_class,
    find_serial_version_uid_field,
    iter_jpa_entity_class_declarations,
    iter_persistent_field_declarations,
    persistent_field_lines,
    persistent_field_signatures,
    serial_version_uid_lines,
    serial_version_uid_value,
)
from validator.java.ast.modifiers import (
    has_query_annotation,
    has_spring_boundary_annotation,
    has_task_changed_query_method,
    is_abstract_top_level_type,
    is_public_top_level_type,
    iter_query_method_declarations,
    node_has_annotation,
    node_has_modifier,
    top_level_type_name,
)
from validator.java.ast.models import (
    ImportDeclaration,
    LocalVariableDeclaration,
    MethodDeclaration,
    VarDeclaration,
    VariableDeclaration,
)
from validator.java.ast.types import (
    declaration_header_line_numbers,
    declaration_simple_name,
    header_has_nosonar,
    is_standard_type_parameter_name,
    iter_generic_type_declarations,
    iter_type_parameter_names,
)
from validator.java.ast.variables import (
    is_optional_type,
    iter_local_variable_declarations,
    iter_var_declarations,
    iter_variable_declarations,
)

__all__ = [
    "ImportDeclaration",
    "LocalVariableDeclaration",
    "MethodDeclaration",
    "VarDeclaration",
    "VariableDeclaration",
    "collect_identifier_usages",
    "comment_body",
    "entity_class_name",
    "find_jpa_entity_class",
    "find_serial_version_uid_field",
    "has_task_reference",
    "is_allowed_comment",
    "is_deprecation_comment",
    "is_gwt_marker_comment",
    "is_javadoc_comment",
    "is_orphan_todo_fixme",
    "is_public_api_javadoc",
    "is_suppression_comment",
    "iter_comments",
    "declaration_header_line_numbers",
    "declaration_simple_name",
    "has_query_annotation",
    "header_has_nosonar",
    "is_standard_type_parameter_name",
    "iter_generic_type_declarations",
    "iter_type_parameter_names",
    "has_task_changed_query_method",
    "iter_query_method_declarations",
    "is_abstract_top_level_type",
    "is_optional_type",
    "is_public_top_level_type",
    "iter_import_declarations",
    "iter_jpa_entity_class_declarations",
    "iter_local_variable_declarations",
    "iter_method_declarations",
    "iter_persistent_field_declarations",
    "iter_var_declarations",
    "iter_variable_declarations",
    "line_in_range",
    "node_has_annotation",
    "node_has_modifier",
    "parse_gwt_section_line_ranges",
    "persistent_field_lines",
    "persistent_field_signatures",
    "serial_version_uid_lines",
    "serial_version_uid_value",
    "top_level_type_name",
]
